name: bank_pit_bwa
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  google_fonts: ^6.1.0
  carousel_slider: ^4.2.1
  url_launcher: ^6.2.4

flutter:
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true
