name: bank_pit_bwa
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  http: ^1.2.0
  intl: ^0.19.0
  url_launcher: ^6.2.4
  bloc: ^8.1.2
  image_picker: ^1.0.7 
  flutter_secure_storage: ^9.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  google_fonts: ^6.1.0
  carousel_slider: ^4.2.1
  another_flushbar: ^1.12.30
  equatable: ^2.0.5
  


flutter:
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true
